language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

notifications:
  slack:
    rooms:
      - secure: "NZHt9kv4ky3+hrH43sW+uFMI+0qPeElkoHoCmvTAsxHW+DPi52UKfc+/CXDrClA+GIi/c5P+gFzAmXvDk9a1Vn/zwVpYhm4gdeWWQDhRSezJEJ5A09RXLNzJxE02zWXVVDbt4ZKECi8tUASDjvCSAcmQB+sdtPKGnnaNkGdYMtu5xJ+xCzQs9+Ft3M5E8X6CtUlt33T+tOM/IgFddEJos7cfoDtdTki0d9CWeMvlEPOxOceBPhgYY7Le8bSATgLRfFmBciFPEpm65Y/dsWX1TwHhZPLU8buXqaUC5jvWCSNmXZsWZZ6FaewtiMlA4Z4jPEVVyJdOwix64GAjvESZk66f7WOb+sblKbxYgLrAHjdOfpbkBFqewxGIUx0cL1kyu2Xo8cM10wTMPrigRX0sv40J9kKykZ8SlB0oEkptrpnWgJZmJUc3cwOLSqhsmvtY0v4npDpiaO46rjdm365QOvexxHCO2btDrGG34w+7yoRSlWrzvkhI3QTx0BHwj1SAOoSGKLAg9W0/eLrTORrdxJgT3R4oG2/mlICi3MBrZ6DCFxl55rQn1b+AbINojfn91yeED/dxVDjXo9T/0lRkR7r02MR7ACNcqDdWzaOngd80/m1s8EnDeNTq/qrOt/+cBuGcR2UT9ZXYVkx7NRuJz71kQo2JJNtA00W68I0Z+u4="
    on_success: change
    on_failure: always

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
#addons:
#    apt:
#        packages:
#            - graphviz
#            - texlive-latex-extra
#            - dvipng

os: linux

python:
    - "2.7"
    - "3.4"
    - "3.5"

before_install:
    # USE UTF8 ENCODING. SHOULD BE DEFAULT, BUT THIS IS INSURANCE AGAINST FUTURE CHANGES
    - export PYTHONIOENCODING=UTF8

    #CHECK INTERACTIVE MATPLOTLIB BACKENDS
    #- export DISPLAY=:99.0
    #- sh -e /etc/init.d/xvfb start

install:
    #- sudo apt-get update
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a

    # ADD STSCI ASTROCONDA CHANNEL
    - conda config --add channels defaults
    - conda config --add channels http://ssb.stsci.edu/astroconda

    # Replace dep1 dep2 ... with your dependencies
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION stsci
    - source activate test-environment
    - python setup.py install

script:
    - nosetests -v stistarg/unit_tests.py
