package:
  name        : stistarg
  version     : '2.4'

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - astropy
    - matplotlib

about:
  home         : 'https://stistarg.readthedocs.io'
  license      : 'BSD-new'
  license_file : 'LICENSE.txt'
  summary      : 'simulates HST/STIS target acquisitions'

extra:
  maintainer       : 'Sean Lockwood'
  maintainer_email : 'help@stsci.edu'
  author           : 'Sean Lockwood & Bralen Berry'
  docs_url         : 'https://stistarg.readthedocs.io'
