package:
  name: stistarg
  version: '2.1a3'

source:
  git_rev: v2.1a3
  git_url: https://github.com/spacetelescope/stistarg.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - argparse
    - astropy
    - matplotlib

about:
  home: http://stistarg.readthedocs.io/en/latest/
  license: BSD-new
  license_file: LICENSE.txt
  summary: simulates HST/STIS target acquisitions

extra:
  maintainer: Sean Lockwood
  maintainer_email: help@stsci.edu
