package:
  name: stistarg
  version: '2.4'

source:
  git_rev: v2.4
  git_url: https://github.com/spacetelescope/stistarg.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - astropy
    - matplotlib

about:
  home: https://stistarg.readthedocs.io
  license: BSD-new
  license_file: LICENSE.txt
  summary: simulates HST/STIS target acquisitions

extra:
  maintainer: Sean Lockwood
  maintainer_email: help@stsci.edu
