name: stistarg
channels:
  - http://ssb.stsci.edu/astroconda
dependencies:
  - numpy
  - matplotlib
  - astropy
  - scipy
  - stistools
  - stsci.convolve
  - stsci.distutils
  - stsci.tools
  - stsci.ndimage
