name: stistarg
channels:
  - http://ssb.stsci.edu/astroconda
dependencies:
  - stsci.convolve
  - stsci.distutils
  - stsci.tools
  - stsci.ndimage
  - sphinxcontrib-programoutput
  - yaml
  - pyyaml
python:
    version: 3.6
